name: Check Style

on: [push, pull_request]

jobs:

  style:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout module
      uses: actions/checkout@master
    - name: Check style
      uses: Nall-chan/action-style@master